### ISSUE TITLE
Support for incomplete batches (padded identities)

### ISSUE THREAD

**Issue by gswirski** [worldcoin/semaphore-mtb#15]
Currently, when I try to insert an incomplete batch (1 or 2 identities out of 3), the prover fails with:

```
20:18:18 INF generating proof
20:18:19 ERR  error="unsatisfied constraint" backend=groth16 curve=BN254 id=476826 nbConstraints=484100
```

This issue showed up while testing https://github.com/worldcoin/signup-sequencer/pull/386

**Comment by kustosz** [comment]
Invalid, this was an error in signup sequencer.
